name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NextJs app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          script: |
            source /home/ec2-user/.nvm/nvm.sh
            cd /home/ec2-user/immersive-sky-expereie
            git pull
            npm install
            npm run build
            pm2 restart all
            echo 'Deployment successful to digital ocean'

