name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build & Deploy Next.js app
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          # Write private key to a file and set permissions
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          # Execute deployment commands on EC2
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} << 'EOF'
             source /home/ec2-user/.nvm/nvm.sh
             cd /home/ec2-user/immersive-sky-expereie
             git pull
             npm install
             npm run build
             pm2 restart all
          EOF
          # Clean up private key file
          rm private_key
